name: Run Python Script Every 3 Hours Starting 9:30 AM ET

on:
  schedule:
    # Note: Cron schedules run in UTC. This schedule corresponds to 9:30 AM, 12:30 PM, 3:30 PM, 6:30 PM, etc., in Eastern Time (ET).
    - cron: '30 13,16,19,22,1,4,7,10 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: |
          python dayV2.py
