name: Run Python Script Every 3 Hours Starting 9:30 AM ET

on:
  schedule:
    # Note: Cron schedules run in UTC. This schedule corresponds to 9:30 AM, 12:30 PM, 3:30 PM, 6:30 PM, etc., in Eastern Time (ET).
    - cron: '30 13,16,19,22,1,4,7,10 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v4

      # Sets up a Python environment for use in actions
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Installs project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance  # Install the required yfinance library
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Executes the main Python script for the stock screener
      - name: Run stock screener
        run: |
          python dayv2.py # Replace with the actual name of your script
